


module CVRice

  module HighGUI

    CV_LOAD_IMAGE_UNCHANGED  = IMREAD_UNCHANGED = -1
    CV_LOAD_IMAGE_GRAYSCALE  = IMREAD_GRAYSCALE = 0
    CV_LOAD_IMAGE_COLOR      = IMREAD_COLOR     = 1
    CV_LOAD_IMAGE_ANYDEPTH   = IMREAD_ANYDEPTH  = 2
    CV_LOAD_IMAGE_ANYCOLOR   = IMREAD_ANYCOLOR  = 4

  end
end

