
# Something in the bundler/gem install process is sanitizing
# the Gem path and I can't find mkrf...
ENV['GEM_PATH'] = ENV['_ORIGINAL_GEM_PATH']

task :opencv_rice do |t|
  #sh "cd #{dir}"
  #ruby "mkrf_conf.rb"
  sh "cd #{t.name} && bundle install && bundle exec ruby mkrf_conf.rb && rake"
end

task :default => :opencv_rice
